services:
  - type: web
    name: juriai-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: PORT
        value: 3001
      # Supabase
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        value: documents
      # General
      - key: MAX_FILE_SIZE
        value: "10485760"
      - key: JWT_SECRET
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
